name: Flask CD

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull the Docker image
      run: |
        docker pull sachigaur/cicd:latest

    - name: Stop existing container
      run: |
        docker stop flask_app || true
        docker rm flask_app || true

    - name: Run Docker container
      run: |
        docker run -d \
        --name flask_app \
        -p 5000:5000 \
        sachigaur/cicd:latest
